version: "3"

networks:
  dev:
    driver: bridge 

services:
  web-api:
    build:
      context: ./otel.api
      dockerfile: Dockerfile
    container_name: web-api
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - web-api-postgres
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dev

  web-api-postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
      target: db
    image: db
    container_name: web-api-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=874521Aa@#
      - POSTGRES_DB=postgres
    cpus: 0.2
    restart: always
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    networks:
      - dev

  

