version: "3"

networks:
  dev:
    driver: bridge 

services:
  web-api1:
    build:
      context: ./backend-dotnet7
      dockerfile: otel.api1/Dockerfile
    container_name: web-api1
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - db-postgres
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dev
  
  web-api2:
    build:
      context: ./backend-dotnet7
      dockerfile: otel.api2/Dockerfile
    container_name: web-api2
    ports:
      - "3001:80"
    restart: always
    depends_on:
      - db-postgres
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dev
  
  web-api3:
    build:
      context: ./backend-dotnet7
      dockerfile: otel.api3/Dockerfile
    container_name: web-api3
    ports:
      - "3002:80"
    restart: always
    depends_on:
      - db-postgres
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dev

  db-postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
      target: db
    image: db
    container_name: db-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=874521Aa@#
      - POSTGRES_DB=postgres
    cpus: 0.2
    restart: always
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    networks:
      - dev

  web-frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: web-frontend-react
    ports:
      - "8080:8080"
    restart: always
    networks:
      - dev
  

