// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using otel.models.EF;

#nullable disable

namespace otel.models.EF.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20230927153411_ini")]
    partial class ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("otel.models.EF.TickerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdjustPrice")
                        .HasPrecision(25, 9)
                        .HasColumnType("numeric(25,9)");

                    b.Property<decimal>("Price")
                        .HasPrecision(25, 9)
                        .HasColumnType("numeric(25,9)");

                    b.Property<decimal>("RemainSize")
                        .HasPrecision(25, 9)
                        .HasColumnType("numeric(25,9)");

                    b.Property<decimal>("Size")
                        .HasPrecision(25, 9)
                        .HasColumnType("numeric(25,9)");

                    b.Property<int>("TickerTemplateModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TickerModels");
                });
#pragma warning restore 612, 618
        }
    }
}
